kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: formatting check
    image: crystallang/crystal:latest-alpine
    commands:
      - crystal tool format --check
  - name: lint
    image: crystallang/crystal:latest-alpine
    commands:
      - apk add curl
      - shards install
      - bin/ameba
  - name: test
    image: crystallang/crystal:latest-alpine
    volumes:
      - name: cache
        path: /root/.cache
    commands:
      - crystal spec

volumes:
  - name: cache
    temp: {}
